version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: some_password
      MYSQL_USER: forge
      MYSQL_PASSWORD: forge
      MYSQL_DATABASE: webapp
    #env_file: ./docker/db/.env
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
    - 3333:3306
    container_name: mysql
  app:
    build: ./docker/php/
    volumes:
      - .:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
        - db
    container_name: php
  web:
    build: ./docker/nginx
    ports:
      - "8000:80"
    depends_on:
        - app
    volumes:
        - ./:/var/www/html
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx