version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    #mysqlの環境変数は.envに記述
    env_file: ./docker/db/.env
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  app:
    build: ./docker/php/
    volumes:
      - .:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
        - db
  web:
    build: ./docker/nginx
    ports:
      - "8000:80"
    depends_on:
        - app
    volumes:
        - ./:/var/www/html
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf